stages:
  - build
  - tests

restore:
  image: microsoft/dotnet:latest
  stage: build
  script:
    - dotnet restore

build:
  image: microsoft/dotnet:latest
  stage: build
  script:
    - dotnet restore -v q
    - dotnet build -v n

frontend-build:
  image: trion/ng-cli
  stage: build
  script:
    - cd Portfolio.ClientApp
    - rm ./package-lock.json
    - npm install
    - ng build --prod

unit-tests:
  image: microsoft/dotnet:latest
  stage: tests
  script:
    - cd Portfolio.Tests/Portfolio.Tests.Unit
    - dotnet test

integration-tests:
  image: docker:latest
  services:
    - docker:dind
  stage: tests
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker build -f integration-tests.Dockerfile -t portfolio_integration_tests .
    - docker-compose -f docker-compose-testing.yml up --abort-on-container-exit  --exit-code-from portfolio_integration_tests