version: "3.4"

services:
    portfolio_integration_tests:
        image: "portfolio_integration_tests"
        container_name: "portfolio_integration_tests"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: "sqlexpress"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"